### ISSUE TITLE
Software licence

### ISSUE THREAD

**Issue by jdaw1** [jdaw1/placemat#2]
There should be a software licence allowing public use. &iquest;Which licence?

My desiderata are:  
* Attribution;  
* Re-usable improvements to code to be shared under the same terms;  
* But one-off changes to the code for generating a particular output need not be shared;
* And, of course, output need not be shared.

&loz; Are these the correct desiderata?
&loz; And if they are, which licence comes closest?

**Comment by mclancy10006** [comment]
as to licenses you probably want something that is reciprocal like GPL or  the LGPL.  https://opensource.org/licenses/GPL-3.0 https://opensource.org/licenses/LGPL-3.0

**Comment by edisonrex** [comment]
I agree with @mclancy10006 - I think the most appropriate license here is GPL 3.0. As we discussed, CC license is probably not as appropriate.

**Comment by jdaw1** [comment]
Thank you for comments. 

GPL3: [done](https://github.com/jdaw1/placemat/blob/main/LICENSE).
