### ISSUE TITLE
Documentation: HTML or Markdown or other?

### ISSUE THREAD

**Issue by jdaw1** [jdaw1/placemat#7]
The documentation has traditionally been in HTML. In what format should it be on GitHub? Obvious candidates are HTML and Markdown.

* HTML?
	- Pages have many images, often floated off to the right with text underneath. Much elegant use is also made of `display: inline-block;`. Markdown can&rsquo;t do these. 
	- But GitHub seems reluctant to act as a webserver. GitHub won&rsquo;t host HTML pages which can be read on a browser. So more machinery would be needed to host elsewhere, machinery which will doubtless break. 

* Markdown?
	- Struggles with complicated formatting. 
	- Easily hosted.

Preferences?

**Comment by mclancy10006** [comment]
Markdown is easier on github

**Comment by jdaw1** [comment]
Done in markdown.
